//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBC.Practice.WCF.Routing.Test.Version2Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.bloggedbychris.com/practice/routing/v2/", ConfigurationName="Version2Service.Version")]
    public interface Version {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bloggedbychris.com/practice/routing/v2/Version/GetVersion", ReplyAction="http://services.bloggedbychris.com/practice/routing/v2/Version/GetVersionResponse" +
            "")]
        string GetVersion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VersionChannel : BBC.Practice.WCF.Routing.Test.Version2Service.Version, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VersionClient : System.ServiceModel.ClientBase<BBC.Practice.WCF.Routing.Test.Version2Service.Version>, BBC.Practice.WCF.Routing.Test.Version2Service.Version {
        
        public VersionClient() {
        }
        
        public VersionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VersionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VersionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VersionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
    }
}
